sudo: required
dist: trusty
language: ruby

before_install:
before_install:
- gem install asciidoctor -v 1.5.2
- gem install tilt
- sudo pip install git+https://github.com/gitenberg-dev/gitberg
- sudo pip install pillow
- sudo pip install cssutils
- sudo pip install docutils
- sudo pip install roman
- sudo pip install git+https://github.com/gitenberg-dev/pg-epubmaker
script:
- VERSION=`ruby -e "require 'yaml'; meta = YAML.load_file('metadata.yaml'); puts meta['_version'];"`
- git clone https://github.com/gitenberg-dev/asciidoctor-htmlbook.git
- sudo pip install -r asciidoctor-htmlbook/gitberg-machine/requirements.txt

- /usr/bin/python -c "from gitenberg import travis; travis.build_epub()"
- ebook-convert book.epub book.mobi
- xvfb-run ebook-convert book.epub book.pdf
branches:
  only:
  - master
notifications:
  webhooks:
    urls:
      - https://unglue.it/api/travisci/webhook
    on_success: always
    on_failure: never
    on_start: never
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: KcElFBDM9KFEL0oaZegsyZ/26U0UwaD68YoEh5M5TtHFe2oxhbk/CFBcHdD5w7kL9ozaVRhe0D/viCPMyMX2wWgLvSJeSP+udN88qE6DXLFLazXYcyaPhx2SoOSvJ3UEC3RFFO9GivQId6gobQ9Z4KI1LgNepWozzwHPSd51xFbe3HrHBatldhteNyfho8InrVlhJ0AX17ja0DLx5HdKWi+N+fTkDb6427rlrqAyjfI7w2eoUsGEJx0YFo+YtTRN/777VcAgSTqnPDHjKlU/zz7rMWiK1Cf+138Pf0KeCymMOJIWHfAtDrsEpzO8+dq3BbO8ZzYF7A33NiYhElOf1Q7dlDlK6l6f1GcOYXgFF2uuHFn+WDM7JiSf6a2bfjtekEQ90PoN5L4ZxUXSg37vzp6OovTZbPKqGsfg512oPPdN1ZdiX0JDy/f24t9eLUHN5Cvm8Ve36ERb9fnLN31xo0sUhX8j/G806KiwxF8aEpMwPR3tJLrLqEsStK1L9a+KzN/zs6RVR/S1WQFqFaDGkSucqLJYijIQGDNBzkoqfqTQOv1xml0nx+DezPG7386tlrfVFbwhzyTVaU4/Qn9XV9YtVjui1gNDL7jiG4hKhz1V/9VWlAQGRhLnt1u4bDTx0q7YhYEuSrl4ZnzqNiS0sGY4tv7EyaMOp1KlQOdOhLg=
  file:
    - book.epub
    - book.mobi
    - book.pdf
  "on":
    repo: GITenberg/Steep-Trails--13-California-Utah-Nevada-Washington-Oregon-the-Grand-Canyon_326
addons:
  apt:
    packages:
    - xsltproc
    - xvfb
    - calibre
    - python-pip
    - git
    - python-dev
    - libjpeg-dev
    - libpng-dev
    - libfreetype6
    - libfreetype6-dev
    - zlib1g-dev
    - python-lxml
    - libxml2-dev
    - libxslt1-dev
    - tidy